# Generated by Django 5.0.7 on 2024-08-04 10:38

import api.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_full_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class')], max_length=10)),
                ('department', models.CharField(choices=[('btech', 'B.Tech'), ('iti', 'ITI'), ('polytech', 'Polytechnic')], max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering')], max_length=5)),
                ('semester_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('rollno', models.IntegerField(unique=True)),
                ('permanent_address', models.TextField()),
                ('applicant_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('applicant_father_phone_number', models.CharField(max_length=15)),
                ('applicant_mother_phone_number', models.CharField(max_length=15)),
                ('father_total_annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('father_occupation_name', models.CharField(max_length=100)),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('bonafide_certificate', models.ImageField(blank=True, max_length=200, null=True, upload_to='hostel_applications/bonafide_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering')], max_length=5)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('admission_based_on', models.CharField(choices=[('JEE', 'Joint Entrance Examination'), ('HPCET', 'Himachal Pradesh Common Entrance Test'), ('SeniorSecondary', 'Senior Secondary'), ('LEET', 'Lateral Entry')], max_length=20)),
                ('marks_scored', models.IntegerField()),
                ('percentage_scored', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class')], max_length=10)),
                ('subcategory', models.CharField(choices=[('Main_AIQ', ',All India Quota'), ('TFW', 'Tuition Fee Waiver'), ('BHA', 'Bhasha'), ('DEF', 'Defence'), ('BPL', 'Below Poverty Line'), ('IRDP', 'Integral rural Deveopment Prog'), ('BA', 'Backward Area'), ('PC/PH', 'Physically Handicapped'), ('SPT', 'Sports'), ('KM', 'Kashmiri Migrant'), ('FF', 'Freedom Fighter'), ('EWS', 'Economically Weaker Section')], max_length=50)),
                ('matric_marks_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aadhaar_no', models.IntegerField(unique=True)),
                ('bank_account_no', models.IntegerField(unique=True)),
                ('bank_account_holder_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('permanent_address', models.TextField()),
                ('father_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('mother_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('candidate_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('round', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('want_hostel', models.BooleanField(default=False)),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('student_passport_size_photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/student_photos/', validators=[api.models.validate_image_size])),
                ('student_aadhaar_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/aadhaar_images/', validators=[api.models.validate_image_size])),
                ('twelfth_certificate_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/12th_certificates/', validators=[api.models.validate_image_size])),
                ('tenth_certificate_image', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/10th_certificates/', validators=[api.models.validate_image_size])),
                ('bonafide_certificate', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/bonafide_certificates/', validators=[api.models.validate_image_size])),
                ('character_certificate', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/character_certificates/', validators=[api.models.validate_image_size])),
                ('migration_certificate', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/migration_certificates/', validators=[api.models.validate_image_size])),
                ('category_certificate', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/student_data/category_certificate/', validators=[api.models.validate_image_size])),
            ],
        ),
    ]
