# Generated by Django 5.0.7 on 2024-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hostelapplication_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelapplication',
            name='department',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('ITI', 'ITI'), ('POLYTECH', 'Polytechnic')], max_length=10),
        ),
    ]
