services:
  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    pull_policy: always
    environment:
      - TERM=xterm
      - DJANGO_SETTINGS_MODULE=backend.settings  
    ports:
      - "5000:5000"
    depends_on:
      - redis
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "backend.wsgi:application"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always      
    ports:
      - "3000:3000"
    command: "npm start "  

networks:
  default:
    driver: bridge